# Generated by Django 3.2 on 2021-04-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('map', models.JSONField(default={'walls': []})),
                ('player', models.JSONField(default={'player': []})),
            ],
        ),
    ]
