# Generated by Django 3.2 on 2021-04-26 07:52

from django.db import migrations, models
import server.characters
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('walls', models.JSONField(default=server.models.get_fresh_default)),
                ('stairs', models.JSONField(default=server.models.get_fresh_default)),
                ('player', models.JSONField(decoder=server.characters.CharacterDecoder, default=server.models.get_fresh_default, encoder=server.characters.CharacterEncoder)),
                ('enemies', models.JSONField(decoder=server.characters.CharacterDecoder, default=server.models.get_fresh_default, encoder=server.characters.CharacterEncoder)),
                ('game_over', models.JSONField(default=server.models.get_fresh_false)),
            ],
        ),
    ]
