# Generated by Django 3.2 on 2021-04-19 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='map',
            new_name='walls',
        ),
    ]
