# Generated by Django 3.2.3 on 2021-05-18 05:42

from django.db import migrations, models
import server.characters
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walls', models.JSONField(default=server.models.get_fresh_default)),
                ('stairs', models.JSONField(default=server.models.get_fresh_default)),
                ('players', models.JSONField(decoder=server.characters.CharacterDecoder, default=server.models.get_fresh_default, encoder=server.characters.CharacterEncoder)),
                ('enemies', models.JSONField(decoder=server.characters.CharacterDecoder, default=server.models.get_fresh_default, encoder=server.characters.CharacterEncoder)),
                ('game_over', models.JSONField(default=server.models.get_fresh_false)),
            ],
        ),
    ]
