# Generated by Django 3.2 on 2021-04-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_map_user_walls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stairs',
            field=models.JSONField(default={'stairs': []}),
        ),
    ]
